title: github.com/frumpled github pages site
description: Self-describing description
# Supported Themes: https://pages.github.com/themes/
#theme: # https://pages.github.com/themes/
remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme

